modLoader = "javafml"
loaderVersion = "[39,)"
license = "GNU LGPL 3.0"

[[mods]]
modId = "thirst"
version = "${file.jarVersion}"
displayName = "Thirst"
authors = "yuuki14202028"
description = '''
Minecraft change real for thirst.
'''
